"""Generates app/test/fixtures/ppg_golden_vectors.json for the Kotlin PPG/fusion
port (ticket 019, module 2).

Calls ppg_reference.py directly - analyse_ppg() and fuse() - so the fixture is
produced by the same reference the validate_*.py suites check, with no
second implementation to keep in step.

That was not always true. ppg_reference.py originally used np.percentile and
np.median where app/lib/signal/ppg.dart uses a plain index-floor into a sorted
list, so this script briefly carried its own Dart-faithful copies of
perfusion_index/perfusion_stability/fuse. ppg_reference.py has since been
corrected to Dart's semantics (see _percentile_floor there), the copies are
gone, and regenerating this fixture reproduces the previous bytes exactly -
which is what confirms the correction was faithful rather than merely close.

Run:  python ml/reference/generate_ppg_golden_vectors.py
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import ppg_reference as ppg  # noqa: E402
import synth_ecg as synth  # noqa: E402

PPG_FS = ppg.PPG_FS


def make_case(name, rhythm, seed, duration=30.0, fill_ms=None, **ppg_kw):
    ecg, truth = synth.synth_ecg(duration_s=duration, rhythm=rhythm, noise_std=8, seed=seed)
    r_ms = ppg.r_peaks_to_ms(truth, 250.0)
    sig, pulse_ms = ppg.synth_ppg(r_ms, duration, PPG_FS, perfusion_fill_ms=fill_ms, seed=seed, **ppg_kw)
    res = ppg.analyse_ppg(sig, PPG_FS)
    fusion = ppg.fuse(list(r_ms), list(res.peaks * 1000.0 / PPG_FS))
    return {
        "name": name,
        "samples": sig.tolist(),
        "expectedPpg": {
            "peaks": res.peaks.tolist(),
            "meanPulseRate": res.mean_pulse_rate,
            "irregularityScore": res.irregularity,
            "perfusionIndex": res.perfusion_index,
            "perfusionStabilityRatio": res.perfusion_stability_ratio,
            "usable": res.usable,
            "beatCount": res.beat_count,
            "failureReason": res.failure_reason,
        },
        "ecgPeakTimesMs": r_ms.tolist(),
        "expectedFusion": {
            "pulseDeficitBpm": fusion.pulse_deficit_bpm,
            "perfusedBeatFraction": fusion.perfused_beat_fraction,
            "nonPerfusingBeats": fusion.non_perfusing_beats,
            "medianPttMs": fusion.median_ptt_ms,
            "valid": fusion.valid,
            "implausible": fusion.implausible,
        },
    }


cases = [
    make_case("nsr_clean_pulse", "nsr", 0),
    make_case("af_deficit", "af", 100, fill_ms=500.0),
    make_case("weak_cold_finger", "nsr", 0, ac_fraction=0.0008),
]

fixture = {
    "_comment": (
        "Generated by ml/reference/generate_ppg_golden_vectors.py for the "
        "Kotlin PPG/fusion port (ticket 019), straight from "
        "ppg_reference.analyse_ppg()/fuse(). Both sides use Dart's index-floor "
        "percentile; do not regenerate with np.percentile/np.median."
    ),
    "fs": PPG_FS,
    "cases": cases,
}

out_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..",
    "app", "test", "fixtures", "ppg_golden_vectors.json",
)
with open(out_path, "w") as f:
    json.dump(fixture, f)

print(f"Wrote {len(cases)} cases to {os.path.abspath(out_path)}")
for c in cases:
    print(f"  {c['name']}: usable={c['expectedPpg']['usable']} "
          f"peaks={len(c['expectedPpg']['peaks'])} "
          f"PI={c['expectedPpg']['perfusionIndex']:.3f}")
