package com.arogyax.signal

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Checks the Kotlin PPG/fusion port against
 * app/test/fixtures/ppg_golden_vectors.json (ticket 019, module 2).
 *
 * Generated by ml/reference/generate_ppg_golden_vectors.py, which uses
 * Dart's actual index-floor percentile and simplified median - NOT
 * ppg_reference.py's np.percentile/np.median directly. See that script's
 * docstring: a real, previously-uncaught drift between the Dart deliverable
 * and its nominal Python mirror, found while writing this test. If this
 * test disagrees with app/lib/signal/ppg.dart or fusion.dart's actual
 * behavior, re-check which side is right before changing either.
 */
class PpgGoldenVectorsTest {
    private val fixture: JSONObject by lazy {
        val file = File("../../app/test/fixtures/ppg_golden_vectors.json")
        require(file.exists()) { "ppg_golden_vectors.json not found at ${file.absolutePath}" }
        JSONObject(file.readText())
    }

    private val fs: Double by lazy { fixture.getDouble("fs") }

    private fun eachCase(block: (name: String, samples: DoubleArray, case: JSONObject) -> Unit) {
        val cases = fixture.getJSONArray("cases")
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val samplesJson = case.getJSONArray("samples")
            val samples = DoubleArray(samplesJson.length()) { samplesJson.getDouble(it) }
            block(case.getString("name"), samples, case)
        }
    }

    @Test
    fun `PPG analysis matches the golden vectors`() {
        eachCase { name, samples, case ->
            val expected = case.getJSONObject("expectedPpg")
            val actual = PpgAnalyser(fs).analyse(samples)

            assertEquals("$name: usable", expected.getBoolean("usable"), actual.usable)
            assertEquals(
                "$name: perfusionIndex",
                expected.getDouble("perfusionIndex"),
                actual.perfusionIndex,
                1e-6,
            )

            val expectedPeaks = expected.getJSONArray("peaks")
            assertEquals("$name: peak count", expectedPeaks.length(), actual.peaks.size)
            for (i in 0 until expectedPeaks.length()) {
                assertEquals("$name: peak[$i]", expectedPeaks.getInt(i), actual.peaks[i])
            }

            if (actual.usable) {
                assertEquals(
                    "$name: meanPulseRate",
                    expected.getDouble("meanPulseRate"),
                    actual.meanPulseRate,
                    1e-6,
                )
                assertEquals(
                    "$name: irregularityScore",
                    expected.getDouble("irregularityScore"),
                    actual.irregularityScore,
                    1e-6,
                )
                assertEquals(
                    "$name: perfusionStabilityRatio",
                    expected.getDouble("perfusionStabilityRatio"),
                    actual.perfusionStabilityRatio,
                    1e-6,
                )
                assertEquals("$name: beatCount", expected.getInt("beatCount"), actual.features.count)
            }
        }
    }

    @Test
    fun `ECG-PPG fusion matches the golden vectors`() {
        eachCase { name, samples, case ->
            val ppgResult = PpgAnalyser(fs).analyse(samples)
            val ecgPeakTimesMsJson = case.getJSONArray("ecgPeakTimesMs")
            val ecgPeakTimesMs = List(ecgPeakTimesMsJson.length()) { ecgPeakTimesMsJson.getDouble(it) }
            val ppgPeakTimesMs = ppgResult.peaks.map { it * 1000.0 / fs }

            val fusion = FusionAnalyser.analyse(
                ecgPeakTimesMs = ecgPeakTimesMs,
                ppgPeakTimesMs = ppgPeakTimesMs,
                ppgUsable = ppgResult.usable,
                simultaneous = true,
            )
            val expected = case.getJSONObject("expectedFusion")

            assertEquals("$name: fusion.valid", expected.getBoolean("valid"), fusion.valid)
            assertEquals(
                "$name: fusion.implausible",
                expected.getBoolean("implausible"),
                fusion.implausible,
            )
            if (fusion.valid) {
                assertEquals(
                    "$name: pulseDeficitBpm",
                    expected.getDouble("pulseDeficitBpm"),
                    fusion.pulseDeficitBpm,
                    1e-6,
                )
                assertEquals(
                    "$name: perfusedBeatFraction",
                    expected.getDouble("perfusedBeatFraction"),
                    fusion.perfusedBeatFraction,
                    1e-6,
                )
                assertEquals(
                    "$name: nonPerfusingBeats",
                    expected.getInt("nonPerfusingBeats"),
                    fusion.nonPerfusingBeats,
                )
                assertEquals(
                    "$name: medianPttMs",
                    expected.getDouble("medianPttMs"),
                    fusion.medianPttMs,
                    1e-6,
                )
            }
        }
    }

    @Test
    fun `fixture actually has cases - a green suite with zero cases proves nothing`() {
        assertTrue(fixture.getJSONArray("cases").length() > 0)
    }
}
